version: "3.7"

services:
  php:
    container_name: php #useful just without docker-swarm
    hostname: php
    build:
      context: docker/php
      target: development #target environment (development, production)
    volumes:
      - ./:/app
      #- php-fpm:/usr/local/sbin/
    networks:
      - overlay

  nginx:
    container_name: nginx
    hostname: nginx
    build:
      context: docker/nginx
    ports:
      - "80:80"
    volumes:
      - ./:/app
      #- php-fpm:/run/php/ volume mapping sock unix php-fpm, you can change for TCP connection on nginx -> .conf -> fastcgi_pass
    networks:
      - overlay
    depends_on:
      - php

#volumes:
#  php-fpm:

networks:
  overlay:
