version: "3.7"

services:
  php:
    container_name: php #useful just without docker-swarm
    hostname: php
    build:
      context: docker/php
      target: development #target environment (development, production)
    volumes:
      - ./:/app
      #- php-fpm:/usr/local/sbin/
    networks:
      - overlay
    deploy:
      mode: replicated
      replicas: 1
      labels: [APP=PHP]
      # service resource management
      resources:
        # Hard limit - Docker does not allow to allocate more
        limits:
          cpus: '0.25'
          memory: 512M
        # Soft limit - Docker makes best effort to return to it
        reservations:
          cpus: '0.25'
          memory: 256M
      # service restart policy
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      # service update configuration
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: continue
        monitor: 60s
        max_failure_ratio: 0.3
      # placement constraint - in this case on 'worker' nodes only
      placement:
        constraints: [node.role == development]

  nginx:
    container_name: nginx
    hostname: nginx
    build:
      context: docker/nginx
    ports:
      - "80:80"
    volumes:
      - ./:/app
      #- php-fpm:/run/php/ volume mapping sock unix php-fpm, you can change for TCP connection on nginx -> .conf -> fastcgi_pass
    networks:
      - overlay
    depends_on:
      - php
    deploy:
      mode: replicated
      replicas: 1
      labels: [APP=PHP, ENV=DEV]
      # service resource management
      resources:
        # Hard limit - Docker does not allow to allocate more
        limits:
          cpus: '0.25'
          memory: 512M
        # Soft limit - Docker makes best effort to return to it
        reservations:
          cpus: '0.25'
          memory: 256M
      # service restart policy
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      # service update configuration
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: continue
        monitor: 60s
        max_failure_ratio: 0.3
      # placement constraint - in this case on 'worker' nodes only
      placement:
        constraints: [node.role == development]

#volumes:
#  php-fpm:

networks:
  overlay: