name: Docker Image CI

on:
  push:
    branches: [php-8.1-jit]
  pull_request:
    branches: [php-8.1-jit]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Build Image
      - uses: actions/checkout@v3
        run: docker-compose build php --no-cache
